# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13LesJC4GXzekLuBefrtfcqlnov8x0Sjx
"""

import azmi035

A = [
    [9, 8, 7],
    [4, 5, 6],
    [1, 2, 3]
]

B = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

hasil_kurang = azmi035.kurang_matriks(A, B)
hasil_tambah = azmi035.tambah_matriks(A, B)
hasil_kali = azmi035.kali_matriks(A, B)



print("\nHasil Pengurangan:")
for baris in hasil_kurang:
    print(baris)


print("Hasil Penjumlahan:")
for baris in hasil_tambah:
    print(baris)


print("\nHasil Perkalian:")
for baris in hasil_kali:
    print(baris)